include:
  - board: eyelash_nano
    shield: eyelash_sofle_right 
  - board: eyelash_nano
    shield: eyelash_sofle_left 
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DMOUSE_PS2_ALT_PINS
  - board: eyelash_nano
    shield: settings_reset
