include:
  - board: eyelash_nano
    shield: eyelash_sofle_right nice_oled
  - board: eyelash_nano
    shield: eyelash_sofle_left nice_oled
    cmake-args: -DDTS_EXTRA_CPPFLAGS=-DMOUSE_PS2_ALT_PINS
  - board: eyelash_nano
    shield: settings_reset
